Varialb rename

diff --git a/scythe/bin/scythe b/scythe/bin/scythe
--- a/scythe/bin/scythe
+++ b/scythe/bin/scythe
@@ -20,21 +20,25 @@ if [ ! -r "$SCYTHE_CMD" ]; then
 	exit 1
 fi
 shift || true
-if [ -z "$SCYTHE_EXAM_ID" ]; then
-	SCYTHE_EXAM_ID="$1"
+if [ -z "$SCYTHE_SESSION_ID" ]; then
+	SCYTHE_SESSION_ID="$1"
 fi
-if  [[ ! "$SCYTHE_EXAM_ID" =~ ^[_[:alpha:][:digit:]]*$ ]]; then
-		echo "scythe: exam id '$SCYTHE_EXAM_ID' must contain alphanumeric and underscore chars only !" >&2
+if  [[ ! "$SCYTHE_SESSION_ID" =~ ^[_[:alpha:][:digit:]]*$ ]]; then
+		echo "scythe: session id '$SCYTHE_SESSION_ID' must contain alphanumeric and underscore chars only !" >&2
 		exit 1
 fi
 
-export SCYTHE_EXAM_ID
+export SCYTHE_SESSION_ID
 shift || true
 source "$SCYTHE_HOME/confs.sh"
 
+if [ ${SCYTHE_USE_SANDBOX+x} ]; then
+	echo "scythe: now docker is no more required for scythe to work, please remove empty SCYTHE_USE_SANDBOX from your confs"
+	exit 1
+fi
 
-if [ ${SCYTHE_USE_SANDBOX+x} ] && [ -z "$SCYTHE_USE_SANDBOX" ]; then
-	echo "scythe: now docker is required for scythe to work, remove empty SCYTHE_USE_SANDBOX from your confs"
+if [ -z "$SCYTHE_TESTER_ID" ]; then
+	echo "scythe: SCYTHE_TEACHER_ID is now deprecated, please edit your confs renaming such var in SCYTHE_TESTER_ID"
 	exit 1
 fi
 
