Trying to improve path handling

diff --git a/scythe/bin/scythe b/scythe/bin/scythe
--- a/scythe/bin/scythe
+++ b/scythe/bin/scythe
@@ -4,18 +4,18 @@ echo1() { echo -e "\033[34m*** $@...\033[0m"; }
 echo2() { echo -e "\033[31m** $@...\033[0m"; }
 echo3() { echo -e "\033[32m* $@...\033[0m"; }
 
-export SCYTHE_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
-export PYTHONPATH="$SCYTHE_HOME/bin/tm:$SCYTHE_HOME/bin/cu"
-export PATH="$SCYTHE_HOME/bin:$PATH"
-
+if [ -z $SCYTHE_HOME ]; then
+	echo "scythe: please set the required environment variables sourcing setpath.sh" 2>&1
+	exit 1
+fi
 
 if [ -z "$1" ]; then
-	echo "shythe: available commands: $(ls -1 "$SCYTHE_HOME/bin/scythe-"* | sed 's/.*\/bin\/scythe-\(.*\)/\1/g' | paste -s -d' ' -)" 2>&1
+	echo "scythe: available commands: $(ls -1 "$SCYTHE_HOME/bin/scythe-"* | sed 's/.*\/bin\/scythe-\(.*\)/\1/g' | paste -s -d' ' -)" 2>&1
 	exit 1
 fi
 SCYTHE_CMD="$SCYTHE_HOME/bin/scythe-$1"
 if [ ! -r "$SCYTHE_CMD" ]; then
-	echo "shyte: command '$1' not found!" >&2
+	echo "scythe: command '$1' not found!" >&2
 	exit 1
 fi
 if [ "$1" == "init" ]; then
@@ -33,7 +33,7 @@ shift
 
 source "$SCYTHE_HOME/../confs/confs.sh"
 if [ ! -r "$EXERCISES" ]; then
-	echo "shythe: exercises list "$EXERCISES" not readable!" 2>&1
+	echo "scythe: exercises list '$EXERCISES' not readable!" 2>&1
 	exit 1
 fi
 
