Only the exercises list is required to build the configuration file, closes #6

diff --git a/scythe/bin/scythe b/scythe/bin/scythe
--- a/scythe/bin/scythe
+++ b/scythe/bin/scythe
@@ -9,33 +9,35 @@ if [ -z "$SCYTHE_HOME" ]; then
 	exit 1
 fi
 
-SCYTHE_CMD="$SCYTHE_HOME/bin/scythe-$1"
-if [ -z "$1" ]; then
+command="$1"
+SCYTHE_CMD="$SCYTHE_HOME/bin/scythe-$command"
+if [ -z "$command" ]; then
 	echo "scythe: available commands: $(ls -1 "$SCYTHE_HOME/bin/scythe-"* | sed 's/.*\/bin\/scythe-\(.*\)/\1/g' | paste -s -d' ' -)" 2>&1
 	exit 1
 fi
 if [ ! -r "$SCYTHE_CMD" ]; then
-	echo "scythe: command '$1' not found!" >&2
+	echo "scythe: command '$command' not found!" >&2
 	exit 1
 fi
-if [ "$1" == "upgrade" ] || [ "$1" == "versions" ]; then
-	NO_FURTHER_ARGS=1
-else
-	NO_FURTHER_ARGS=
-fi
 shift
-
 SCYTHE_CONF="$1"
-if [ -z "$NO_FURTHER_ARGS" ] && [ -z "$SCYTHE_CONF" ]; then
-	echo "scythe: please specify the conf name!" >&2
-	exit 1
-fi
 shift
-
 source "$SCYTHE_HOME/confs.sh"
-if [ -z "$NO_FURTHER_ARGS" ] && [ ! -r "$TM_SETTINGS" ]; then
-	echo "scythe: configuration '$TM_SETTINGS' not readable!" >&2
-	exit 1
-fi
+
+case "$command" in
+	upgrade|versions)
+	;;
+	prepare)
+		if [ ! -r "$EXERCISES" ]; then
+		    echo "scythe: exercises list '$EXERCISES' not readable!" >&2
+		    exit 1
+		 fi
+	;;
+	*)
+		if [ ! -r "$TM_SETTINGS" ]; then
+			echo "scythe: configuration '$TM_SETTINGS' not readable!" >&2
+			exit 1
+		fi
+esac
 
 source "$SCYTHE_CMD" "$@"
