Added a test to exlude SCYTHE_EXAM_ID values that can confuse the server. Closes #8.

diff --git a/scythe/bin/scythe b/scythe/bin/scythe
--- a/scythe/bin/scythe
+++ b/scythe/bin/scythe
@@ -5,7 +5,7 @@ echo2() { echo -e "\033[31m** $@...\033[0m"; }
 echo3() { echo -e "\033[32m* $@...\033[0m"; }
 
 if [ -z "$SCYTHE_HOME" ]; then
-	echo "scythe: please set the required environment variables sourcing setpath.sh" 2>&1
+	echo "scythe: please set the required environment variables sourcing setenv.sh" 2>&1
 	exit 1
 fi
 
@@ -23,6 +23,11 @@ shift
 if [ -z "$SCYTHE_EXAM_ID" ]; then
 	SCYTHE_EXAM_ID="$1"
 fi
+if  [[ ! "$SCYTHE_EXAM_ID" =~ ^[_[:alpha:][:digit:]]*$ ]]; then
+		echo "scythe: exam id '$SCYTHE_EXAM_ID' must contain alphanumeric and underscore chars only !" >&2
+		exit 1
+fi
+
 export SCYTHE_EXAM_ID
 shift
 source "$SCYTHE_HOME/confs.sh"
